import Head from "next/head";
import Image from "next/image";
import Carousel from "../components/Carousel";
import Featured from "../components/Featured";
import styles from "../styles/Home.module.css";

export default function Home() {
  const array = ["item1", "2", "3", "4", "5"];
  return (
    <div className={styles.container}>
      <Head>
        <title>Food Dhandha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Featured /> */}
      <Carousel arrayItems={array} />
    </div>
  );
}
